# Generated by Django 4.2.6 on 2024-11-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='webReview',
        ),
    ]
